### ISSUE TITLE
Crashes when combined with location access request

### ISSUE THREAD

**Issue by ShMcK** [idehub/react-native-google-analytics-bridge#111]
I'm having issues with "react-native-google-analytics-bridge" since requesting location permissions.

Any ideas what might be causing this or how to fix it?

### Steps to reproduce:

1. install "react-native-google-analytics-bridge": "4.0.2", "react-native": "0.38.1"
2. Add the following to your android/app/src/AndroidManifest.xml:

```js
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<!-- or <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> -->
```

3. run "react-native android". App crashes on startup (device only, works on simulator).

4. comment out the permission request in AndroidManifest.xml and watch the app work again.

### StackTrace (from Android Studio)

```
02-16 22:48:56.851 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
02-16 22:48:56.851 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
02-16 22:48:56.851 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$5>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$5>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$10>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$10>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$2>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$2>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$9>
02-16 22:48:56.862 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$9>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$8>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$8>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$7>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$7>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$1>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$1>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$6>
02-16 22:48:56.872 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$6>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$4>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$4>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$zza>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$3>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzd$3>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.GeofencingRequest>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.GeofencingRequest>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$1>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$1>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.GeofencingRequest>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.GeofencingRequest>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$2>
02-16 22:48:56.882 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$2>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$zza>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$3>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzf$3>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationSettingsRequest>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationSettingsRequest>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationSettingsRequest>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationServices$zza>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzq$1>
02-16 22:48:56.892 19774-19774/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.zzq$1>
02-16 22:48:57.002 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.GeofencingRequest>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationRequest>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationSettingsRequest>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.LocationRequestInternal>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.internal.LocationRequestInternal>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:57.012 19774-19808/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.location.LocationAvailability>
02-16 22:48:57.012 19774-19808/? E/AndroidRuntime: FATAL EXCEPTION: LocationService
                                                   Process: com.and, PID: 19774
                                                   java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Landroid/os/Looper;ILcom/google/android/gms/common/internal/zzg;Lcom/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks;Lcom/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener;)V in class Lcom/google/android/gms/common/internal/zzk; or its super classes (declaration of 'com.google.android.gms.common.internal.zzk' appears in /data/app/com.and-1/base.apk)
                                                       at com.google.android.gms.location.internal.zzb.<init>(Unknown Source)
                                                       at com.google.android.gms.location.internal.zzl.<init>(Unknown Source)
                                                       at com.google.android.gms.location.LocationServices$1.zzo(Unknown Source)
                                                       at com.google.android.gms.location.LocationServices$1.zza(Unknown Source)
                                                       at com.google.android.gms.common.api.GoogleApiClient$Builder.zza(Unknown Source)
                                                       at com.google.android.gms.common.api.GoogleApiClient$Builder.zzvq(Unknown Source)
                                                       at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by cbrevik** [comment]
Hi @ShMcK, thanks for the reproduction steps, I'll test this later. It looks like it doesn't find `LocationService`. Are you explicitly using that class anywhere?

**Comment by ShMcK** [comment]
It seems to fail when used in conjunction with [react-native-ua](https://github.com/globocom/react-native-ua). Perhaps both share a common class. 

I'll close this issue, as it seems more related to react-native-ua.
