### ISSUE TITLE
App in android with react native 0.21 is crashing on launch

### ISSUE THREAD

**Issue by amourya-systango** [idehub/react-native-google-analytics-bridge#126]
FATAL EXCEPTION: AsyncTask #1
                                                                java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                    at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                                    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                                    at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                    at java.lang.Thread.run(Thread.java:841)
                                                                 Caused by: java.lang.IllegalAccessError: tried to access method android.support.v4.net.ConnectivityManagerCompat.<init>:(Lcom/facebook/react/bridge/ReactApplicationContext;)V from class com.facebook.react.modules.netinfo.NetInfoModule
                                                                    at com.facebook.react.modules.netinfo.NetInfoModule.<init>(NetInfoModule.java:55)
                                                                    at com.facebook.react.shell.MainReactPackage.createNativeModules(MainReactPackage.java:67)
                                                                    at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:793)
                                                                    at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:730)
                                                                    at com.facebook.react.ReactInstanceManagerImpl.access$600(ReactInstanceManagerImpl.java:91)
                                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:184)
                                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:169)
                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by cbrevik** [comment]
Which version of this module are you running? 

Why do you believe it is this module by the way? I cannot see any note of it in your stack trace.

**Comment by amourya-systango** [comment]
4.0.3

**Comment by amourya-systango** [comment]
Hey, I have solved my problem. It's not your library problem rather the problem is on my end. I was using gcm google service and your library using analytics google service then on both gradle files the different versions are conflicted. I correct it by putting the same version in your library gradle file like com.google.android.gms:play-services-analytics:8.1.0 so finally my problem has resolved.

**Comment by cbrevik** [comment]
Hi, glad you solved it @amourya-systango.

You don't have to edit the gradle file of my library by the way. If you force a certain version in your own projects gradle file, then my library should use that version instead. See [the repository wiki](https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#android-build-problem) for more details.
