### ISSUE TITLE
FATAL EXCEPTION for trackMultiProductsPurchaseEvent on android

### ISSUE THREAD

**Issue by flavordaaave** [idehub/react-native-google-analytics-bridge#129]
On iOS the app runs as expected but when calling `trackMultiProductsPurchaseEvent` on my android app, it crashes with following output in adb logcat:

```
04-18 17:46:19.798  3432  3468 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-18 17:46:19.798  3432  3468 E AndroidRuntime: Process: com.myapp, PID: 3432
04-18 17:46:19.798  3432  3468 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: couldn't find key id in dynamic object
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridge.getPurchaseTransaction(GoogleAnalyticsBridge.java:180)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridge.trackMultiProductsPurchaseEvent(GoogleAnalyticsBridge.java:138)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:746)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
04-18 17:46:19.798  3432  3468 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
```

I call it with something like this:
```
trackMultiProductsPurchaseEvent(
  [
    {
      product: 'ID123',
      name: 'Productxyz',
      category: 'catId123',
      brand: 'brandname',
      variant: 'variation a',
      price: 100,
      quantity: 1,
      couponCode: '',
    }
    ...
  ], {
    id: 'orderId123',
    affiliation: 'My App',
    revenue: '500',
    tax: 90,
    shipping: 10,
    couponCode: '',
  }, 'checkout', 'payed order')
```

**Comment by flavordaaave** [comment]
My fault... If I would have read the error I would have noticed that the `id` property was missing for product...
