### ISSUE TITLE
Android app crashing on trackScreenView

### ISSUE THREAD

**Issue by novakben** [idehub/react-native-google-analytics-bridge#147]
This is my log:

```07-05 13:17:07.178 16857 17388 I GAv4    : Google Analytics 11.0.20 is starting up. To enable debug logging on a device run:
07-05 13:17:07.178 16857 17388 I GAv4    :   adb shell setprop log.tag.GAv4 DEBUG
07-05 13:17:07.178 16857 17388 I GAv4    :   adb logcat -s GAv4
07-05 13:17:07.275 16857 17388 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzanz>
07-05 13:17:07.275 16857 17388 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzanz>
07-05 13:17:07.350 16857 17413 W GAv4    : AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.
07-05 13:17:07.394 16857 17388 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
07-05 13:17:07.399 16857 17413 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.
07-05 13:17:07.418 16857 17413 W GAv4    : AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
07-05 13:17:07.436 16857 16857 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzanz>
07-05 13:17:07.436 16857 16857 D AndroidRuntime: Shutting down VM
07-05 13:17:07.438 16857 17413 E GAv4    : Successfully bound to service but never got onServiceConnected callback
07-05 13:17:07.896 16857 16857 E AndroidRuntime: FATAL EXCEPTION: main
07-05 13:17:07.896 16857 16857 E AndroidRuntime: Process: com.thinger, PID: 16857
07-05 13:17:07.896 16857 16857 E AndroidRuntime: java.lang.IncompatibleClassChangeError: com.google.android.gms.internal.zzanz
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at com.google.android.gms.internal.zzamp.onServiceConnected(Unknown Source)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-05 13:17:07.896 16857 16857 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-05 13:17:07.898  1551  3197 W ActivityManager:   Force finishing activity com.thinger/.MainActivity
07-05 13:17:07.901  1220  1396 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
07-05 13:17:07.907  1551  3197 D         : HostConnection::get() New Host Connection established 0x9eaed180, tid 3197
07-05 13:17:07.921  1220  1220 E EGL_emulation: tid 1220: eglCreateSyncKHR(1660): error 0x3004 (EGL_BAD_ATTRIBUTE)
07-05 13:17:07.958  1551  3197 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
07-05 13:17:07.969  1551  1565 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{ff92b4e u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{d8f714c 16857 com.thinger/10069/u0 remote:afc1d7f}: process crashing
07-05 13:17:08.009  1551  1600 I OpenGLRenderer: Initialized EGL, version 1.4
07-05 13:17:08.015  1551  2048 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
07-05 13:17:08.036  1220  1396 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
07-05 13:17:08.047  1551  1600 E EGL_emulation: tid 1600: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
07-05 13:17:08.047  1551  1600 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9b29c360, error=EGL_BAD_MATCH
07-05 13:17:08.049  1220  1608 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
07-05 13:17:08.053  1220  1608 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
07-05 13:17:08.463  1551  1565 W ActivityManager: Activity pause timeout for ActivityRecord{794e8cb u0 com.thinger/.MainActivity t70 f}
07-05 13:17:08.504  1220  1396 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
07-05 13:17:08.518  1903  2073 E EGL_emulation: tid 2073: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
07-05 13:17:08.518  1903  2073 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa0613d00, error=EGL_BAD_MATCH
07-05 13:17:08.523  1220  1608 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
07-05 13:17:08.532  1220  1608 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
07-05 13:17:09.071  1903  2073 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
07-05 13:17:09.071  1903  2073 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
07-05 13:17:13.573  2253  2262 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/metrics.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
07-05 13:17:13.575  2253  2262 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/help_responses.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
07-05 13:17:13.578  2253  2262 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/auto_complete_suggestions.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
07-05 13:17:18.471  1551  1565 W ActivityManager: Activity destroy timeout for ActivityRecord{794e8cb u0 com.thinger/.MainActivity t70 f}
07-05 13:18:00.074  1220  1331 D hwcomposer: hw_composer sent 140 syncs in 60s

```

**Comment by cbrevik** [comment]
Are you using any other libraries which also depends on Play Services? Seems like it is crashing on that.

**Comment by novakben** [comment]
Nope.

**Comment by novakben** [comment]
Found the solution,
In the package build.grade I changed to a specific version of play services and it works:
```
    //compile 'com.google.android.gms:play-services-analytics:+'
    compile 'com.google.android.gms:play-services-analytics:9.+'
```

**Comment by novakben** [comment]
Nope didn't work.
Now it says there's a duplicates gms... entry:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
        at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzai$zze.class
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzai$zze.class
        at com.android.build.gradle.internal.transforms.JarMergingTransform.transform(JarMergingTransform.java:118)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 77 more
Caused by: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzai$zze.class
        at com.android.build.gradle.internal.transforms.JarMerger.addJar(JarMerger.java:179)
        at com.android.build.gradle.internal.transforms.JarMergingTransform.transform(JarMergingTransform.java:108)
```

**Comment by novakben** [comment]
This happens when trying to deploy to a device

**Comment by cbrevik** [comment]
What is the contents of your `android/app/build.gradle file` @novakben?

Really seems like there is some other lib you're using which is making the GA dependency of this lib crash.

**Comment by novakben** [comment]
Boom!

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        applicationId "com.thinger"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.1"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}
dependencies {
    compile project(':react-native-billing')
    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-fbads')
    compile project(':react-native-fast-image')
    compile project(':react-native-oauth')
    compile project(':react-native-vector-icons')
    compile project(':react-native-share')
    compile project(':react-native-linear-gradient')
    compile fileTree(dir: "libs", include: ["*.jar"])
    //compile "com.android.support:appcompat-v7:23.0.1"
    //compile "com.android.support:appcompat-v7:25.2.0"
    //compile('com.facebook.android:facebook-android-sdk:4.22.1')
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    //compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

**Comment by novakben** [comment]
Also I should mention that this happens only in react-native cli.
On Android Studio it runs great on the device.

**Comment by cbrevik** [comment]
You haven't placed any dependencies in the other `android/build.gradle` file? Firebase or something?

Seems weird it won't work on CLI, which it runs though AS, since both use the same gradle build.

Can you try going into the `android` and running `./gradlew clean`, then running the CLI again? You're running `react-native run-android` or something?

**Comment by novakben** [comment]
Only running works in Android Studio, if I try to generate APK it breaks with the same error.

react-native-fbads has this in build.gradle:
```
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.facebook.android:audience-network-sdk:4.22.1'
}
```

is it possible it has something to do with `compile 'com.facebook.android:audience-network-sdk:4.22.1'` ?

Regarding that it shouldn't crash, I changed in this lib dependencies to this:

```
dependencies {
    compile 'com.facebook.react:react-native:+'
    //compile 'com.google.android.gms:play-services-analytics:+'
    compile 'com.google.android.gms:play-services-analytics:9+'
}
```

If I don't, the app crashes on trying to do anything with the lib (views / events /etc)

**Comment by novakben** [comment]
Maybe com.facebook.android:audience-network-sdk is using a very old version of google play services?

**Comment by cbrevik** [comment]
Don't know if you have checked out the wiki, but I have this guide regarding forcing a specific version:
https://github.com/idehub/react-native-google-analytics-bridge/wiki/Troubleshooting#android-build-problem

That is to say:
```gradle
compile("com.google.android.gms:play-services-analytics:9.0.0"){
    force = true
}
```

Inside your `android/app/build.gradle`. Then you won't have to change the lib dependency for my library. If it's `com.facebook.android:audience-network-sdk` using a specific Play Services version, find out which, and input that version (instead of `9.0.0`) and it should work with my library.

**Comment by novakben** [comment]
I love you.

So this `Audience Network SDK » 4.22.1`, uses this:
`com.google.android.gms » play-services-ads | 8.4.0`

So as you suggested. this solves it 😃😃😃😃

```
compile("com.google.android.gms:play-services-analytics:8.4.0"){
        force = true
    }
```

I tried troubleshooting just didn't realise where the duplicate is coming from.
Thanks a lot!!
