### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by sibelius** [idehub/react-native-google-analytics-bridge#188]
```jsx
Fatal Exception: java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:301)
       at com.google.android.gms.internal.zztn.zzqC(Unknown Source)
       at com.google.android.gms.internal.zztn.zzmS(Unknown Source)
       at com.google.android.gms.internal.zzsa.initialize(Unknown Source)
       at com.google.android.gms.internal.zzsc.<init>(Unknown Source)
       at com.google.android.gms.internal.zzsc.zzan(Unknown Source)
       at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
       at com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridge.getTracker(GoogleAnalyticsBridge.java:37)
       at com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridge.setUser(GoogleAnalyticsBridge.java:265)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:2319)
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:292)
       at com.google.android.gms.internal.zztn.zzqC(Unknown Source)
       at com.google.android.gms.internal.zztn.zzmS(Unknown Source)
       at com.google.android.gms.internal.zzsa.initialize(Unknown Source)
       at com.google.android.gms.internal.zzsc.<init>(Unknown Source)
       at com.google.android.gms.internal.zzsc.zzan(Unknown Source)
       at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
       at com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridge.getTracker(GoogleAnalyticsBridge.java:37)
       at com.idehub.GoogleAnalyticsBridge.GoogleAnalyticsBridge.setUser(GoogleAnalyticsBridge.java:265)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by sibelius** [comment]
maybe this could happen https://stackoverflow.com/a/30062632/2628278
