### ISSUE TITLE
TypeError: Cannot read property 'setAppName' of undefined when running tests with Jest

### ISSUE THREAD

**Issue by imdadahad** [idehub/react-native-google-analytics-bridge#189]
In our application we import and setup the google analytics tracker:

```
const tracker = new GoogleAnalyticsTracker(trackingId)

tracker.setAppName("AppName")

GoogleAnalyticsSettings.setDispatchInterval(10)
```

We have a simple test that doesn't actually do anything apart from creating and getting an app context.

We receive the following error:

```
 FAIL  tests/index.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'setAppName' of undefined

      at GoogleAnalyticsTracker.setAppName (node_modules/react-native-google-analytics-bridge/src/GoogleAnalyticsTracker.js:212:37)
      at Object.<anonymous> (app/config/analytics.js:10:9)
      at Object.<anonymous> (app/navigators/mainTab/index.js:7:16)
      at Object.<anonymous> (app/reducers/navigation.js:3:12)
      at Object.<anonymous> (app/reducers/index.js:3:17)
      at Object.<anonymous> (app/config/store.js:3:12)
      at Object.<anonymous> (app/index.js:4:12)
      at Object.<anonymous> (tests/index.test.js:2:12)
          at Generator.next (<anonymous>)
          at Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

We've cleaned npm packages, re-run the react-native link and followed solutions from other issues that mentioned downgrading the RN version etc. but still have had no luck. 

Any ideas?

**Comment by cbrevik** [comment]
I'd recommend mocking the library when running tests.

**Comment by imdadahad** [comment]
We plan to mock this along with other libraries that make external calls. However I am curious as to what’s causing this.

Imdad Ahad

**Comment by cbrevik** [comment]
The internal native bridge is not available during test, and that is why it is undefined: https://github.com/idehub/react-native-google-analytics-bridge/blob/master/src/GoogleAnalyticsTracker.js#L212

**Comment by imdadahad** [comment]
Oh I see. Thanks for that. 

Imdad
