### ISSUE TITLE
Duplicate implementation of com.google.android.gms.internal.measurement

### ISSUE THREAD

**Issue by klooperator** [idehub/react-native-google-analytics-bridge#281]
Hi,
after I install rngab I get this error on build:
```
Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: com.google.android.gms.internal.measurement.zzdx
        at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
        at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
        at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
        at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:121)
        at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:122)
        at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:40)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:110)
        at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)
        ... 45 more
```

### Environment

```
...
"dependencies": {
    "lodash.padstart": "^4.6.1",
    "moment": "^2.22.2",
    "native-base": "^2.8.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-admob-dfp": "^2.0.0-beta.3.9",
    "react-native-google-analytics-bridge": "^6.0.0",
    "react-native-onesignal": "^3.2.7",
    "react-native-router-flux": "^4.0.1",
    "react-native-sentry": "^0.39.0",
    "react-native-share": "^1.1.2",
    "react-native-video": "^3.2.1",
    "react-native-youtube": "^1.1.0",
    "react-redux": "^5.0.7",
    "react-style-proptype": "^3.2.2",
    "redux": "^4.0.0",
    "redux-rest-fetcher": "../../redux-rest-fetcher"
  },
...
```
```
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
    }
```
Anyone else got this? 
I think that it conflicts with react-native-admob-dfp, because it is the only one that uses com.google.android.gms. 
I tried the latest version also ( then downgraded). I also tried fixing the googlePlayServicesVersion in gradle, but to no avail.

**Comment by cbrevik** [comment]
> I think that it conflicts with react-native-admob-dfp, because it is the only one that uses com.google.android.gms.

It might be that as well, but I also see that `react-native-onesignal` depends on `com.onesignal:OneSignal:3.10.1`, which in turn has an older `play-services-base` (10.2.1, 12.1.0) as Compile Dependency: http://mvnrepository.com/artifact/com.onesignal/OneSignal/3.10.1

Also see that `googlePlayServicesVersion` is not supported by either of the other dependencies, so that won't do much good.

I'd go for the "advanced solution" from this wiki-post I wrote: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems#the-advanced-solution

Just force the RNGAB dependencies to be version `12.1.0`. You might have to force `com.google.android.gms:play-services-ads` to be the same version since [`react-native-admob-dfp` depends on that](https://github.com/fmtekcan/react-native-admob-dfp/blob/0883493f8a373fd1c94e4eb0bcdac63917b36848/android/build.gradle#L21).
