### ISSUE TITLE
Build fails on app:transformClassesWithMultidexlistForDevDebug with TransformException

### ISSUE THREAD

**Issue by brenohq** [idehub/react-native-google-analytics-bridge#302]
### Environment

react-native: 0.55.4
react-native-google-analytics-bridge: 6.1.2

### Expected Behavior

I want be able to build the project.

### Actual Behavior

I installed react-native-google-analytics-bridge normally and, then I linked libraries and the project stop building with these error:

OBS: Notice that on my the defaultConfig option multiDexEnabled is set true.

```
...
:app:compileDevDebugSources UP-TO-DATE
:app:transformClassesWithDexBuilderForDevDebug UP-TO-DATE
:app:transformClassesWithMultidexlistForDevDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDevDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```

### My app/build.gradle

```gradle
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
}

apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

project.ext.react = [
        entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableProguardInReleaseBuilds = false

project.ext {
    googlePlayServicesVersion = "+"
}

android {
    compileSdkVersion 26
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "br.com.equals"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 196
        versionName "2.5.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    lintOptions {
        checkReleaseBuilds false
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }
    flavorDimensions "equals"
    productFlavors {
        dev {
            dimension "equals"
        }
        prod {
            dimension "equals"
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    dexOptions {
        keepRuntimeAnnotatedClasses false
        javaMaxHeapSize "4g"
    }
}

dependencies {
    compile project(':lottie-react-native')
    compile project(':react-native-appsee')
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.android.support:multidex:1.0.3"
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
    implementation "com.google.firebase:firebase-messaging:17.1.0"
    implementation(project(':react-native-firebase')) {
        transitive = false
    }
    implementation project(':react-native-text-input-mask')
    implementation project(':react-native-charts-wrapper')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-config')
    implementation project(':react-native-video')
    implementation project(':react-native-i18n')
    implementation project(':react-native-device-info')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation project(':react-native-svg')
    implementation('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-google-analytics-bridge')
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by nthegedus** [comment]
Same error here

**Comment by mrcluc** [comment]
Same error here :cry:

**Comment by cbrevik** [comment]
Hi guys. Can any of you provide a minimum working sample project that reproduces this error?

**Comment by brenohq** [comment]
@cbrevik I tried to create from scratch another https://github.com/infinitered/ignite project and the library react-native-google-analytics-bridge worked normally.

It seems to be an conflict with react-native-firebase, and I could not reproduce this.

**Comment by cbrevik** [comment]
For conflicts with `react-native-firebase` I recommend looking at this wiki post I wrote: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems

**Comment by brenohq** [comment]
@cbrevik I fixed the build problem by adding the following line in the end of the gradle.properties file
```
googlePlayServicesVersion=11.+
```
:tada: :tada: :tada: Thanks!

**Comment by felipemillhouse** [comment]
After follow these steps https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems I get that problem:
## Error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```
## app/build.gradle
```
apply plugin: "com.android.application"

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    signingConfigs {
      debug {
          storeFile file('keystores/debug.keystore')
          keyAlias 'androiddebugkey'
          keyPassword 'android'
          storePassword 'android'
      }
    }

    defaultConfig {
        applicationId "com.phyxable"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        versionCode 3
        versionName "1.0.2"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
      release {
        if (project.hasProperty('MYAPP_RELEASE_STORE_FILE1')) {
          storeFile file(MYAPP_RELEASE_STORE_FILE1)
          storePassword MYAPP_RELEASE_STORE_PASSWORD1
          keyAlias MYAPP_RELEASE_KEY_ALIAS1
          keyPassword MYAPP_RELEASE_KEY_PASSWORD1
        }
      }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-google-analytics-bridge')
    implementation project(':react-native-orientation-locker')
    implementation project(':react-native-onesignal')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-firebase')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-video')
    implementation "com.google.firebase:firebase-core:16.0.3"
    implementation "com.google.firebase:firebase-database:16.0.2"
    implementation "com.google.firebase:firebase-storage:16.0.2"
    implementation ("com.google.android.gms:play-services-base:15.0.1"){force = true;}
    implementation ("com.google.android.gms:play-services-auth:16.0.0"){force = true;}
    implementation "com.google.firebase:firebase-auth:16.0.3"
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms"
    }
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-fast-image')
}


// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```
## build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "26.1.0"
        googlePlayServicesVersion = "16.0.1"
        //googlePlayServicesVersion = "15.0.1"
        //supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:4.0.1'
        //classpath 'com.google.gms:google-services:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {url "$rootDir/../node_modules/react-native/android"}
        maven {url "https://maven.google.com"}
        maven { url "https://jitpack.io" }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```
## settings.gradle
```
rootProject.name = 'phyxableapp'
include ':react-native-google-analytics-bridge'
project(':react-native-google-analytics-bridge').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-analytics-bridge/android')
include ':react-native-orientation-locker'
project(':react-native-orientation-locker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-orientation-locker/android')
include ':react-native-onesignal'
project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')
include ':rn-fetch-blob'
project(':rn-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/rn-fetch-blob/android')
include ':react-native-image-crop-picker'
project(':react-native-image-crop-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-crop-picker/android')
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-google-signin'
project(':react-native-google-signin').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-signin/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-fast-image'
project(':react-native-fast-image').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fast-image/android')

include ':app'
```
## manifest
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.phyxableapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@drawable/icon"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:launchMode="singleTop"
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
          <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by Devid2727** [comment]
I am facing same problem 

`om.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/measurement/zzwe;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

**Comment by cbrevik** [comment]
Look at the advanced section of my wiki post: https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems#the-advanced-solution

I see many using different libs which have conflicting Play Services dependencies, like OneSignal, Firebase, my lib, react-native-google-signin, etc. You really have to take care to notice what your dependencies are depending on. 

Setting `googlePlayServicesVersion=11.+` for example will not work alongside Firebase. My lib works with that version, but it will conflict with Firebase. OneSignal has similar issues.
