### ISSUE TITLE
Questions: Can I use this together with firebase? Or will it have a conflict?

### ISSUE THREAD

**Issue by iadcg** [idehub/react-native-google-analytics-bridge#310]
I have react native app and is using firebase (https://github.com/invertase/react-native-firebase) for push notification and analytics.
I am also planning to use Google Analytics for the same tracking purpose
But when I try to add the Google Analytics native react bridge, I always get this error

```
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/iad/.gradle/caches/transforms-1/files-1.1/firebase-analytics-16.0.4.aar/8c474ea709b9cb6276ac972808548f4e/jars/classes.jar
....
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
at com.android.tools.r8.D8.run(D8.java:90)
at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
... 7 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.internal.measurement.zzwv is referenced as an interface from com.google.android.gms.internal.measurement.zzfq$zzb$zza.
at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
... 10 more
```

**Comment by iadcg** [comment]
This is my gradle file

```
apply plugin: "com.android.application"
apply plugin: 'io.fabric'

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        applicationId "com.company.appname"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 5
        // IMPORTANT:
        // When you increment this value and upload a new native android version,
        // you need to comment the line: configuration.codeBundleId = 'xxx' in App/Lib/CrashReporter.js
        versionName "1.0.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    flavorDimensions "version"
    productFlavors {
        dev {
            dimension "version"
        }
        prod {
            dimension "version"
        }
    }

    buildTypes {
        debug {
            // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.
            buildConfigField "String", "CODEPUSH_KEY", '""'
            signingConfig signingConfigs.release
        }

        releaseStaging {
            buildConfigField "String", "CODEPUSH_KEY", '""'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            matchingFallbacks = ['release']
        }

        release {
            buildConfigField "String", "CODEPUSH_KEY", '""'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { 
        }
    }
    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.webkit:android-jsc:r224109'
    }
}

dependencies {
    compile project(':react-native-google-analytics-bridge')
    compile project(':bugsnag-react-native')
    compile project(':react-native-appsflyer')
    compile project(':@segment_analytics-react-native')
    compile project(':react-native-appsee')
    compile project(':react-native-gesture-handler')
    compile project(':react-native-video')
    compile project(':react-native-vector-icons')
    implementation project(':react-native-code-push')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-pdf')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-firebase')
    implementation project(':tipsi-stripe')
    implementation project(':react-native-imei')
    implementation project(':react-native-keep-awake')
    implementation project(':react-native-material-kit')
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-facebook-account-kit')
    implementation 'com.facebook.android:facebook-android-sdk:4.34.0'
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-google-signin')
    implementation project(':react-native-keychain')
    implementation project(':react-native-svg')
    implementation project(':react-native-config')
    implementation project(':react-native-device-info')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.facebook.react:react-native:+'
    // From node_modules
    implementation(project(':react-native-google-signin')) {
        exclude group: "com.google.android.gms" // very important
    }
    implementation 'com.google.zxing:core:3.3.2'
    implementation 'com.drewnoakes:metadata-extractor:2.9.1'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.google.android.gms:play-services-base:16.0.1'
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    compile project(':react-native-open-settings')
    implementation 'com.appsee:appsee-android:+'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.8@aar') {
        transitive = true
    }
    implementation("com.google.android.gms:play-services-measurement-base:16.0.5")
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

// NOTE: please refer  https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/37
// as it is required by com.google.gms:google-services:4.0.1
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

```

**Comment by cbrevik** [comment]
Hi, see https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems if you have issues building

**Comment by iadcg** [comment]
@cbrevik Mine is quite different I think and not a dependency version conflict issue

**Comment by cbrevik** [comment]
"Error: Type com.google.android.gms.internal.measurement.zzwv is referenced as an interface from com.google.android.gms.internal.measurement.zzfq$zzb$zza." points to it being a Play Services conflict.

The wiki post I linked describes the problem, and you really should look it over.

**Comment by cbrevik** [comment]
You're using other RN modules which depend upon Play Services as well, like `react-native-google-signin`. Might be more that I don't see right away.

I'd recommend looking over your dependencies, and see how they might conflict. The error message might vary, but the cause is usually the same.
